# Ficheiro: codemagic.yaml
# Roteiro de instruções para o Codemagic construir o app para iOS (versão corrigida e otimizada)
workflows:
  ios-app-build:
    name: Construir App AIGEO para iOS
    instance_type: mac_mini_m1 # Define o tipo de Mac virtual a ser usado
    environment:
      node: 20
      xcode: 15
      cocoapods: default
    scripts:
      - name: Instalar, construir e sincronizar o projeto
        script: | 
          # Para o script se houver qualquer erro
          set -e

          # 1. Instala as dependências do NPM (incluindo @ionic/cli e @capacitor/cli do seu package.json)
          echo ">>> Instalando dependências do projeto..."
          npm install

          # 2. (A CORREÇÃO) Instala o pacote da plataforma iOS do Capacitor
          echo ">>> Instalando plataforma Capacitor iOS..."
          npm install @capacitor/ios

          # 3. Constrói a versão web do app
          echo ">>> Compilando a aplicação web com Ionic..."
          ionic build

          # 4. Sincroniza os ficheiros web com o projeto nativo
          #    Este comando já executa 'add' se a plataforma não existir, tornando o passo anterior desnecessário.
          echo ">>> Sincronizando com Capacitor para iOS..."
          ionic capacitor sync ios
      
      - name: Instalar dependências nativas (CocoaPods)
        script: |
          # Navega para a pasta do iOS e instala os Pods
          echo ">>> Instalando dependências nativas com CocoaPods..."
          cd ios/App && pod install

      - name: Configurar assinatura de código e construir .ipa
        script: |
          # Define o diretório do projeto para os comandos seguintes
          cd .. # Volta para a raiz do projeto (onde está a pasta 'ios')

          # Assina a aplicação usando os perfis carregados no Codemagic
          echo ">>> Configurando a assinatura de código..."
          xcode-project use-profiles

          # Constrói o ficheiro .ipa final
          echo ">>> Construindo o ficheiro .ipa..."
          xcode-project build-ipa --workspace "ios/App/App.xcworkspace" --scheme "App"

    artifacts:
      # Onde encontrar o ficheiro final para download
      - build/ios/ipa/*.ipa
