# Ficheiro: codemagic.yaml
# Roteiro de instruções para o Codemagic construir o app para iOS (versão corrigida e otimizada)
workflows:
  ios-app-build:
    name: Construir App AIGEO para iOS
    instance_type: mac_mini_m1 # Define o tipo de Mac virtual a ser usado
    environment:
      node: 20
      xcode: 15
      cocoapods: default
    scripts:
      - name: Instalar, construir e sincronizar o projeto
        script: | 
          # Para o script se houver qualquer erro
          set -e

          # 1. Instala as dependências do NPM
          echo ">>> Instalando dependências do projeto..."
          npm install

          # 2. Instala o pacote da plataforma iOS do Capacitor
          echo ">>> Instalando plataforma Capacitor iOS..."
          npm install @capacitor/ios

          # 3. Constrói a versão web do app
          echo ">>> Compilando a aplicação web com Ionic..."
          ionic build

          # 4. Sincroniza os ficheiros web com o projeto nativo
          echo ">>> Sincronizando com Capacitor para iOS..."
          ionic capacitor sync ios
      
      - name: Instalar dependências, assinar e construir o app iOS
        script: |
          # Para o script se houver qualquer erro
          set -e

          # 1. Instala as dependências nativas (CocoaPods) sem mudar de diretório
          echo ">>> Instalando dependências nativas com CocoaPods..."
          pod install --project-directory=ios/App

          # 2. (CORREÇÃO) Assina a aplicação especificando o projeto correto
          echo ">>> Configurando a assinatura de código..."
          xcode-project use-profiles --project="ios/App/App.xcodeproj"

          # 3. Constrói o ficheiro .ipa final
          echo ">>> Construindo o ficheiro .ipa..."
          xcode-project build-ipa --workspace "ios/App/App.xcworkspace" --scheme "App"

    artifacts:
      # Onde encontrar o ficheiro final para download
      - build/ios/ipa/*.ipa
